spring:
  datasource:
    username: root
    password: ysy123123
    url: jdbc:mysql://14.235.172.71:3306/commodity?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
      access-key: LTAI5tGJ1c8hnwwXXX
      secret-key: hS72N9CjrxZCI6SzRXXXX

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos的地址ip加端口
  application:
    name: ysyliving-commodity
  #1. 关闭thymeleaf的缓存, 这样当前端页面变化时，就可以看到效果
  #2. 在实际的生产环境, 需要将cache 设置为true ,开启缓存,提高效率
  thymeleaf:
    cache: false

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #配置主键自增
      logic-delete-value: 0 #逻辑删除值(默认是1, 老韩这里调整成自己的)
      logic-not-delete-value: 1 #逻辑未删除值(默认是0, 老韩这里调整成自己的)
  configuration:
    #这里我们配置输出底层的sql,方便我们观察sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
