server:
  port: 7070


spring:
  cloud:
    #配置OSS
    alicloud:
      access-key: LTAI5tGJ1c8hnwwkSWmNcWdt
      secret-key: hS72N9CjrxZCI6SzRYCIdeUYFZSpyH
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: seckill-bucket
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: ysyliving-service